"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

add_newline = false

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_status]
disabled = true

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "
